version: "3.3"

services:
  wpdb:
    image: mysql:5.7
    volumes:
      - ./.db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308
  wordpress:
    depends_on:
      - wpdb
    build: .
    volumes:
      - wordpress_data:/var/www/html
      - ./:/var/www/html/wp-content/plugins/anspress-question-answer
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wpdb:3308
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1

volumes:
  wordpress_data: {}