name: Deploy

on:
  push:
    branches: [ master, dev ]
  release:
    types: [ published ]

jobs:
  build-deploy:
    name: Deploy to demo and dev sites
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
        ref: dev

    - name: Archive readme
      uses: actions/upload-artifact@v2
      with:
        name: readme
        path: anspress-question-answer.php

    - name: Upload to development site
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.DEV_SFTP_HOST }}
        username: ${{ secrets.DEV_SFTP_USERNAME }}
        password: ${{ secrets.DEV_SFTP_PASSWORD }}
        source: "*"
        target: ${{ secrets.DEV_PLUGIN_PATH }}

  wp-release:
    name: New release on WordPress.org
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run build
        sed -i -e 's/ANSPRESS_CURRENT_DEV_VERSION/${{ github.event.release.tag_name }}/g' /anspress-question-answer.php
        sed -i -e 's/ANSPRESS_CURRENT_DEV_VERSION/${{ github.event.release.tag_name }}/g' /readme.txt

    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: anspress-question-answer
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ github.workspace }}/anspress-question-answer.zip
        asset_name: anspress-question-answer.zip
        asset_content_type: application/zip