name: Release

on:
  release:
    types: [ published ]

  workflow_dispatch:
    inputs:
      refSha:
        description: 'branch'
        required: true
        default: dev

jobs:
  wp-release:
    name: New release on WordPress.org
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current tag
      run: |
        CURRENT_TAG=$(echo "${GITHUB_REF/refs\/tags\//}")
        echo "Current tag is: $CURRENT_TAG"

    - name: Build
      run: |
        npm install
        npm run build
        sed -i "s/0.0.1-dev-rc1/$CURRENT_TAG/g" ./anspress-question-answer.php
        rm package.json
        rm package-lock.json
        rm docker-compose.yml
        rm Dockerfile

    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: anspress-question-answer
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ github.workspace }}/anspress-question-answer.zip
        asset_name: anspress-question-answer.zip
        asset_content_type: application/zip
